query AccountStatement($id: ID!, $first: Int = 20) {
  account(id: $id) {
    name
    balance {
      amount
      currency
    }
    transactions(first: $first) {
      edges {
        node {
          postedAt
          description
          entries {
            amount {
              amount
              currency
            }
            direction
            counterpartyAccount {
              name
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}